### PR TITLE
Last CMake/fixes PR

### PR DESCRIPTION
**Pull request by silvioprog**
It compiles on Linux (tested on Ubuntu 16.04 64 bits) and Windows (tested on MinGW-w64 32 and 64 bits) and allow to use the library with other environments like Delphi, Free Pascal, Java (JNI), Python etc.

### CODE REVIEW

**Comment by babelouest** [comment]
Again, I'm ok for cmake and porting it as is for other OS, but not ok for the other languages support on the core library.
Porting orcania to other languages can be made as a different github project.

**Comment by silvioprog** [comment]
> ... but not ok for the other languages support on the core library

Hm... same to Ulfius? :-/

**Comment by babelouest** [comment]
Yes, same for Ulfius/Yder/Hoel.
Take a look at [Wrapper Library](https://en.wikipedia.org/wiki/Wrapper_library) models.
To do so, IMHO, your best move is to encapsulate the libraries calls in a wrapper that you will make the interface between the core libraries and the other languages.
It's easy and clean, and like that there won't be unneccessary code in the core libraries.

**Comment by silvioprog** [comment]
Thanks again for replying dude! It sounds good and related to some parts of https://github.com/babelouest/ulfius/issues/34 (I'll reply there as soon as I possible ...). I'm already using wrappers to map other libraries, so probably I'll use the same way. :-)

**Pull request closed without merging**
